#  https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc
server:
  port: 8001
spring:
  application:
    name: rookie-nacos-service
  cloud:
    nacos:
      config:

        server-addr: 127.0.0.1:8848 #Nacos地址
        #file-extension: yaml #这里我们获取的yaml格式的配置
        #不同的服务可以归类到同一分组。
        group: DEFAULT_GROUP
      discovery:
        server-addr: 127.0.0.1:8848 #Nacos地址
  config:
    import:
      - optional:nacos:rookie-nacos-config-dev.yaml  # 监听 DEFAULT_GROUP:test.yml
      #这个yaml在生产环境需要配置到nacos配置中心中，如上
      - optional:classpath:rookie-nacos-service-dev.yaml