#  https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc
server:
  port: 8081
spring:
  application:
    name: rookie-nacos-config
  cloud:
    nacos:
      config:

        server-addr: 127.0.0.1:8848 #Nacos地址
        #file-extension: yaml #这里我们获取的yaml格式的配置
        #不同的服务可以归类到同一分组。
        group: DEFAULT_GROUP
#用于进行租户粒度的配置隔离。不同的命名空间下，可以存在相同的 Group 或 Data ID 的配置。Namespace 的常用场景之一是不同环境的配置的区分隔离，例如开发测试环境和生产环境的资源（如配置、服务）隔离等。
#  config:
#    import:
#      - optional:nacos:nacos-config.properties  # 监听 DEFAULT_GROUP:test.yml
  config:
    import:
      - optional:nacos:rookie-nacos-config-dev.yaml  # 监听 DEFAULT_GROUP:test.yml
#user:
#  name: abc
#  age: 23

## application.yml
#spring:
#  cloud:
#    nacos:
#      config:
#        group: DEFAULT_GROUP
#        server-addr: 127.0.0.1:8848
#  config:
#    import:
#      - optional:nacos:test.yml  # 监听 DEFAULT_GROUP:test.yml
#      - optional:nacos:test01.yml?group=group_01 # 覆盖默认 group，监听 group_01:test01.yml
#      - optional:nacos:test02.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
#      - nacos:test03.yml # 在拉取nacos配置异常时会快速失败，会导致 spring 容器启动失败