#  https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc
server:
  port: 8081
spring:
  application:
    name: rookie-api-gateway
