#  https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc
server:
  port: 8081
spring:
  application:
    name: rookie-nacos-openfeign-service
  cloud:
    nacos:
      config:

        server-addr: 127.0.0.1:8848 #Nacos地址
        #file-extension: yaml #这里我们获取的yaml格式的配置
        #不同的服务可以归类到同一分组。
        group: DEFAULT_GROUP
      discovery:
        server-addr: 127.0.0.1:8848 #Nacos地址
    loadbalancer:
      cache: # 负载均衡缓存配置
        enabled: true # 开启缓存
        ttl: 5s # 设置缓存时间
        capacity: 256 # 设置缓存大小
      retry: # 重试配置
        enabled: true
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 1



  config:
    import:
      - optional:nacos:rookie-nacos-config-dev.yaml  # 监听 DEFAULT_GROUP:test.yml


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://rookie-nacos-service

feign:
  client:
    config:
      default: # Feign调用超时配置
        connectTimeout: 5000
        readTimeout: 5000
